// Paired editorial copy. Published titles and DOI identifiers stay in their original language.
export const copy = {
  en: {
    lang: "en",
    title: "Jun Xu — Learning, with room to wander",
    description:
      "Jun Xu explores how people learn, make sense of information, and live with AI. A personal space for research, questions, and conversation.",
    name: "Jun Xu",
    skip: "Skip to content",
    nav: ["Home", "Research atlas", "Publications", "Say hello"],
    menu: "Menu",
    deck: {
      previous: "Previous page",
      next: "Next page",
      hint: "Scroll to turn the page",
      page: "Page",
      directions: "Research directions",
      field: "Beyond the screen",
      publication: "Publications",
    },
    intro: "EDUCATION, TECHNOLOGY & THE HUMAN SIDE",
    hero: ["Learning, with", "room to wander."],
    lead: "Hi, I’m Jun. I explore how we learn, what we trust, and where AI fits into the picture.",
    explore: "Explore my research atlas",
    hello: "Let’s exchange ideas",
    photoAlt: "Jun outdoors on a grassland beneath a cloud-filled sky",
    photoNote: "A little room beyond the screen.",
    photoSide: "Same curiosity. A different view.",
    about: "A researcher. An unfinished learner.",
    bio: "I study in the field of educational technology at East China Normal University. My interests connect self-regulated learning, educational AI, and the ways people share and interpret knowledge.",
    bioEnd:
      "This is a place to share the questions behind the papers—and leave room for new ones.",
    orcid: "Find me on ORCID",
    interests: ["Learning", "Artificial intelligence", "Knowledge", "People"],
    readingTitle: "Published work.<br>Ideas out in the world.",
    readingIntro:
      "All published papers in this collection, from newest to oldest. Explore by topic, or follow a DOI to the published record.",
    filters: [
      "All topics",
      "Learning & AI",
      "Knowledge & trust",
      "Teachers & communities",
      "Digital society",
    ],
    paperLink: "Read paper",
    fullRecord: "View my ORCID record",
    contactTitle: "A shared question<br>is a good beginning.",
    contactIntro:
      "Working on something related? Have a different perspective? I’d love to hear it.",
    email: "Write an email",
    copy: "Copy email",
    copied: "Email copied.",
    copyFailed: "Please select and copy the email address above.",
    formTitle: "Or leave a note here",
    nameLabel: "Your name",
    optional: "optional",
    contactLabel: "How can I reply?",
    contactPlaceholder: "Email or another way to reach you",
    messageLabel: "Your note",
    placeholder: "What’s on your mind?",
    submit: "Send a private note",
    privacy:
      "Notes are not displayed publicly. The site records visit and message metadata, including IP addresses, for site administration and spam prevention.",
    sending: "Sending…",
    sent: "Thanks—your note has arrived.",
    failed: "Your note could not be sent. Please try again or use email.",
    limited: "Too many notes in a short time. Please try later or use email.",
    length:
      "Please keep your note and contact details within 1,000 characters in total.",
    countLabel: "Characters, including contact details",
    noscript:
      "The reading links work without JavaScript. To get in touch, please use email.",
    footer: "Always learning. Happy to be in conversation.",
    top: "Back to top",
    results: "papers",
    empty: "No papers in this topic.",
  },
  zh: {
    lang: "zh-CN",
    title: "徐俊 — 学习，也留一点漫游的余地",
    description:
      "徐俊的个人空间：分享关于学习、信息与人工智能的研究和问题，期待交流与新的视角。",
    name: "徐俊",
    skip: "跳到正文",
    nav: ["首页", "研究图谱", "已发表成果", "聊一聊"],
    menu: "导航",
    deck: {
      previous: "上一页",
      next: "下一页",
      hint: "下滑翻到下一页",
      page: "页码",
      directions: "研究方向",
      field: "屏幕之外",
      publication: "已发表成果",
    },
    intro: "教育、技术，以及其中的人",
    hero: ["学习，也留一点", "漫游的余地。"],
    lead: "你好，我是徐俊。我关心我们如何学习、信任什么，以及人工智能在其中扮演怎样的角色。",
    explore: "逛逛我的研究图谱",
    hello: "交换一些想法",
    photoAlt: "徐俊在草原上，身后是铺满云朵的天空",
    photoNote: "屏幕之外，也留一点空间。",
    photoSide: "换个风景，好奇心依旧。",
    about: "做研究，也一直在学。",
    bio: "我在华东师范大学学习教育技术学，关注自我调节学习、教育人工智能，以及人们分享和理解知识的方式。",
    bioEnd: "在这里，分享论文背后的问题，也为新的问题留一个位置。",
    orcid: "在 ORCID 找到我",
    interests: ["学习", "人工智能", "知识", "人"],
    readingTitle: "把思考写下来，<br>让想法走得更远。",
    readingIntro:
      "收录现有全部已发表论文，按年份从新到旧排列。可以按话题浏览，也可以通过 DOI 查看正式发表记录。",
    filters: [
      "全部话题",
      "学习与 AI",
      "知识与信任",
      "教师与共同体",
      "数字社会",
    ],
    paperLink: "阅读论文",
    fullRecord: "查看我的 ORCID 记录",
    contactTitle: "一个共同的问题，<br>就是很好的开始。",
    contactIntro: "正在做相关的研究？或是有不一样的看法？很期待听到你的想法。",
    email: "写封邮件",
    copy: "复制邮箱",
    copied: "邮箱已复制。",
    copyFailed: "请选中上方邮箱地址并复制。",
    formTitle: "也可以在这里留个言",
    nameLabel: "怎么称呼你",
    optional: "选填",
    contactLabel: "如何回复你",
    contactPlaceholder: "邮箱或其他联系方式",
    messageLabel: "留言",
    placeholder: "你在想些什么？",
    submit: "私密发送",
    privacy:
      "留言不会公开展示。网站会记录访问与留言的元数据（包括 IP 地址），用于站点管理和防止垃圾留言。",
    sending: "正在发送……",
    sent: "收到啦，谢谢你的留言。",
    failed: "留言未能发送，请重试或通过邮件联系。",
    limited: "短时间内留言较多，请稍后再试或通过邮件联系。",
    length: "留言与联系方式合计请控制在 1,000 字符以内。",
    countLabel: "字符数，包含联系方式",
    noscript: "不启用 JavaScript 也能阅读论文。如需交流，请通过邮箱联系。",
    footer: "一直在学，也期待与你聊聊。",
    top: "返回顶部",
    results: "篇论文",
    empty: "该话题下暂无论文。",
  },
};
