// Paired editorial copy. Published titles and DOI identifiers stay in their original language.
export const copy = {
  en: {
    lang: "en",
    title: "Jun Xu — Learning, with room to wander",
    description:
      "Jun Xu explores how people learn, make sense of information, and live with AI. A personal space for research, questions, and conversation.",
    name: "Jun Xu",
    skip: "Skip to content",
    nav: ["Curiosities", "Selected reading", "Say hello"],
    menu: "Menu",
    intro: "EDUCATION, TECHNOLOGY & THE HUMAN SIDE",
    hero: ["Learning, with", "room to wander."],
    lead: "Hi, I’m Jun. I explore how we learn, what we trust, and where AI fits into the picture.",
    explore: "Follow a curiosity",
    hello: "Let’s exchange ideas",
    photoAlt: "Jun outdoors on a grassland beneath a cloud-filled sky",
    photoNote: "A little room beyond the screen.",
    photoSide: "Same curiosity. A different view.",
    about: "A researcher. An unfinished learner.",
    bio: "I work in educational technology at East China Normal University. My interests connect self-regulated learning, educational AI, and the ways people share and interpret knowledge.",
    bioEnd:
      "This is a place to share the questions behind the papers—and leave room for new ones.",
    orcid: "Find me on ORCID",
    interests: ["Learning", "Artificial intelligence", "Knowledge", "People"],
    curiosityTitle: "Good questions<br>leave the door open.",
    curiosityIntro:
      "Three threads I keep coming back to. Pick one and see where it leads.",
    questions: [
      {
        topic: "Learning",
        title: "When help is everywhere, how do we learn to help ourselves?",
        text: "I’m interested in what learners do before, during, and after a task: setting goals, checking their understanding, and deciding what to try next.",
        link: "Explore AI and self-regulated learning",
        target: "paper-srl",
        words: ["Plan", "Act", "Reflect"],
      },
      {
        topic: "AI & people",
        title: "What should AI make easier—and what is worth the effort?",
        text: "An easier task is not always a better learning experience. I’m curious about how educational AI can support understanding while leaving space for learners’ own judgment.",
        link: "Explore the AI literacy review",
        target: "paper-literacy",
        words: ["Support", "Agency", "Understanding"],
      },
      {
        topic: "Knowledge & trust",
        title: "What makes a piece of information worth trusting?",
        text: "Who speaks, how a message is shared, and what others say can shape our judgments. I study how these social and technical cues relate to trust and knowledge sharing.",
        link: "Explore trust and danmaku",
        target: "paper-trust",
        words: ["Source", "Message", "Trust"],
      },
    ],
    readingTitle: "A few things<br>I’ve been thinking through.",
    readingIntro:
      "Selected papers, with a little context. Follow the DOI for the published record.",
    filters: ["All topics", "Learning & AI", "Knowledge & trust"],
    paperLink: "Read paper",
    fullRecord: "More publications on ORCID",
    contactTitle: "A shared question<br>is a good beginning.",
    contactIntro:
      "Working on something related? Have a different perspective? I’d love to hear it.",
    email: "Write an email",
    copy: "Copy email",
    copied: "Email copied.",
    copyFailed: "Please select and copy the email address above.",
    formTitle: "Or leave a note here",
    nameLabel: "Your name",
    optional: "optional",
    contactLabel: "How can I reply?",
    contactPlaceholder: "Email or another way to reach you",
    messageLabel: "Your note",
    placeholder: "What’s on your mind?",
    submit: "Send a private note",
    privacy:
      "Notes are not displayed publicly. The site records visit and message metadata, including IP addresses, for site administration and spam prevention.",
    sending: "Sending…",
    sent: "Thanks—your note has arrived.",
    failed: "Your note could not be sent. Please try again or use email.",
    limited: "Too many notes in a short time. Please try later or use email.",
    length:
      "Please keep your note and contact details within 1,000 characters in total.",
    countLabel: "Characters, including contact details",
    noscript:
      "The reading links work without JavaScript. To get in touch, please use email.",
    footer: "Always learning. Happy to be in conversation.",
    top: "Back to top",
    results: "papers shown",
    empty: "No papers in this topic.",
  },
  zh: {
    lang: "zh-CN",
    title: "徐俊 — 学习，也留一点漫游的余地",
    description:
      "徐俊的个人空间：分享关于学习、信息与人工智能的研究和问题，期待交流与新的视角。",
    name: "徐俊",
    skip: "跳到正文",
    nav: ["好奇的问题", "精选阅读", "聊一聊"],
    menu: "导航",
    intro: "教育、技术，以及其中的人",
    hero: ["学习，也留一点", "漫游的余地。"],
    lead: "你好，我是徐俊。我关心我们如何学习、信任什么，以及人工智能在其中扮演怎样的角色。",
    explore: "从一个问题出发",
    hello: "交换一些想法",
    photoAlt: "徐俊在草原上，身后是铺满云朵的天空",
    photoNote: "屏幕之外，也留一点空间。",
    photoSide: "换个风景，好奇心依旧。",
    about: "做研究，也一直在学。",
    bio: "我在华东师范大学从事教育技术相关研究，关注自我调节学习、教育人工智能，以及人们分享和理解知识的方式。",
    bioEnd: "在这里，分享论文背后的问题，也为新的问题留一个位置。",
    orcid: "在 ORCID 找到我",
    interests: ["学习", "人工智能", "知识", "人"],
    curiosityTitle: "好的问题，<br>让对话保持开放。",
    curiosityIntro:
      "这是我反复回到的三个话题。选一个，看看它会把我们带向哪里。",
    questions: [
      {
        topic: "学习",
        title: "当帮助随处可得，我们如何学会帮助自己？",
        text: "我关心学习者在任务开始前、进行中和结束后的行动：设定目标、检查理解，以及决定下一步尝试什么。",
        link: "读读 AI 与自我调节学习",
        target: "paper-srl",
        words: ["计划", "行动", "反思"],
      },
      {
        topic: "AI 与人",
        title: "AI 应该让什么变容易，又有哪些努力值得保留？",
        text: "任务更轻松，并不总意味着学习更好。我好奇教育人工智能如何帮助人理解，同时为学习者自己的判断留出空间。",
        link: "读读 AI 素养研究综述",
        target: "paper-literacy",
        words: ["支持", "自主性", "理解"],
      },
      {
        topic: "知识与信任",
        title: "是什么让一条信息值得信任？",
        text: "谁在说、信息如何传播、其他人怎么回应，都可能影响我们的判断。我研究这些社会和技术线索与信任、知识共享之间的关系。",
        link: "读读信任与弹幕互动",
        target: "paper-trust",
        words: ["来源", "信息", "信任"],
      },
    ],
    readingTitle: "把一些思考，<br>慢慢写成论文。",
    readingIntro:
      "几篇精选论文，以及它们关注的问题。通过 DOI 可查看正式发表记录。",
    filters: ["全部话题", "学习与 AI", "知识与信任"],
    paperLink: "阅读论文",
    fullRecord: "在 ORCID 查看更多论文",
    contactTitle: "一个共同的问题，<br>就是很好的开始。",
    contactIntro: "正在做相关的研究？或是有不一样的看法？很期待听到你的想法。",
    email: "写封邮件",
    copy: "复制邮箱",
    copied: "邮箱已复制。",
    copyFailed: "请选中上方邮箱地址并复制。",
    formTitle: "也可以在这里留个言",
    nameLabel: "怎么称呼你",
    optional: "选填",
    contactLabel: "如何回复你",
    contactPlaceholder: "邮箱或其他联系方式",
    messageLabel: "留言",
    placeholder: "你在想些什么？",
    submit: "私密发送",
    privacy:
      "留言不会公开展示。网站会记录访问与留言的元数据（包括 IP 地址），用于站点管理和防止垃圾留言。",
    sending: "正在发送……",
    sent: "收到啦，谢谢你的留言。",
    failed: "留言未能发送，请重试或通过邮件联系。",
    limited: "短时间内留言较多，请稍后再试或通过邮件联系。",
    length: "留言与联系方式合计请控制在 1,000 字符以内。",
    countLabel: "字符数，包含联系方式",
    noscript: "不启用 JavaScript 也能阅读论文。如需交流，请通过邮箱联系。",
    footer: "一直在学，也期待与你聊聊。",
    top: "返回顶部",
    results: "篇论文",
    empty: "该话题下暂无论文。",
  },
};

export const papers = [
  {
    id: "srl",
    topic: "learning",
    year: "2026",
    journal: "British Journal of Educational Technology",
    doi: "https://doi.org/10.1111/bjet.70058",
    title:
      "AI support in self-regulated learning: A decade of technological evolution and meta-analysis",
    en: "How does AI support different phases of self-regulated learning? A meta-analysis of 35 studies examines the effects and the conditions that shape them.",
    zh: "AI 如何支持自我调节学习的不同阶段？这项纳入 35 项研究的元分析考察其作用，以及影响这些作用的条件。",
  },
  {
    id: "trust",
    topic: "knowledge",
    year: "2026",
    journal: "Aslib Journal of Information Management",
    doi: "https://doi.org/10.1108/AJIM-01-2026-0111",
    title:
      "Trust the messenger, then the message: Unpacking the cross-route logic of danmaku engagement",
    en: "What happens when knowledge videos meet real-time audience comments? A study of source cues, trust, and knowledge adoption on Bilibili.",
    zh: "知识视频与实时弹幕相遇，会发生什么？这项研究关注 B 站情境中的来源线索、信任与知识采纳。",
  },
  {
    id: "literacy",
    topic: "learning",
    year: "2026",
    journal: "Behaviour & Information Technology",
    doi: "https://doi.org/10.1080/0144929X.2026.2711024",
    title:
      "Mapping the evolving landscape of AI literacy research: An integrative review combining bibliometric analysis and thematic synthesis",
    en: "What do we mean by AI literacy? Bibliometric analysis and thematic synthesis trace how this research field is taking shape.",
    zh: "当我们谈论 AI 素养时，究竟在谈什么？文献计量与主题综合呈现这一研究领域逐渐形成的知识结构。",
  },
  {
    id: "sharing",
    topic: "knowledge",
    year: "2024",
    journal: "Journal of Information Science",
    doi: "https://doi.org/10.1177/01655515241293754",
    title:
      "The impact of mobile social media on knowledge sharing among vocational school teachers: A social cognitive career perspective",
    en: "How do teachers share what they know? A study of the psychological and technological factors behind knowledge sharing through mobile social media.",
    zh: "教师如何分享自己所知？这项研究考察移动社交媒体情境下知识共享背后的心理与技术因素。",
  },
];
